server:
  port: 2015
spring:
  application:
    name: product-service
  datasource:
    username: root
    password: 123456
    url:jdbc:mysql:///stitch?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
